# Good reference: https://github.com/deviantony/docker-elk

version: '2.1'

services:
  elasticsearch:
    image: elasticsearch:7.13.4
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    ports:
      - 5601:5601
    environment:
      - elasticsearch.hosts="http://elasticsearch:9200"
    networks:
      - elk

networks:
  elk:
    driver: bridge

