name: cb docker

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.1.0
        with:
          compose-file: "./tests/docker_files/cb_docker-compose.yml"

      - name: Wait on
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http://localhost:8080

      - name: Check running containers
        run: docker ps -a

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Nox Dependencies
        run: python -m pip install poetry nox nox-poetry pyparsing==3.0.4 sphinx

      - name: Final package list
        run: pip freeze


      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
        with:
          args: pytest ./tests/docker_cb_api_test.py
