name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Compose Action
      uses: isbang/compose-action@v1.1.0
      with:
        compose-file: "./tests/docker_files/cb_docker-compose.yml"

    - name: Wait on
      uses: iFaxity/wait-on-action@v1
      with:
        resource: http://localhost:8080

    - name: Check running containers
      run: docker ps -a