name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f ./tests/docker_files/cb_docker-compose.yml up -d
    - name: Wait on
      uses: iFaxity/wait-on-action@v1
      with:
        resource: http://localhost:8080

    - name: Check running containers
      run: docker ps -a