name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    name: "Test (python: ${{ matrix.python-version }}, sphinx: ${{ matrix.sphinx-version }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.6", "3.8", "3.9"]
        sphinx-version: ["3.2", '3.5', '4.1', '4.2']
        exclude:
          - python-version: "3.6"
            sphinx-version: "3.2"
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Nox Dependencies
        run: |
          python -m pip install poetry nox nox-poetry
      - name: Run Tests
        run: nox --non-interactive --session "tests-${{ matrix.python-version }}(sphinx='${{ matrix.sphinx-version }}')" -- --full-trace

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Nox Dependencies
        run: |
          python -m pip install poetry nox nox-poetry
      - name: Run Lint
        run: nox --non-interactive --session lint -- --full-trace

# Deactivated, as somehow the external services get invoked, even if ON_CI is set to True
#  linkcheck:
#    name: Docs-Linkcheck
#    runs-on: ubuntu-20.04
#    env:
#      ON_CI: True
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set Up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.9"
#      - name: Install Nox Dependencies
#        run: |
#          python -m pip install poetry nox nox-poetry
#      - name: Run LinkCheck
#        run: nox --non-interactive --session linkcheck -- --full-trace
